export const comicsList = [
    {
        id: 'child-pose',
        title: 'Childs pose',
        description: 'A little comic for Instagram',
        thumbnail: '/comics/child_pose/1.jpg',
        images: [
            '/comics/child_pose/1.jpg',
            '/comics/child_pose/2.jpg',
            '/comics/child_pose/3.jpg',
            '/comics/child_pose/4.jpg',
            '/comics/child_pose/5.jpg',
            '/comics/child_pose/6.jpg',
            '/comics/child_pose/7.jpg',
            '/comics/child_pose/8.jpg',
            '/comics/child_pose/9.jpg',
            '/comics/child_pose/10.jpg',
        ],
    },
    {
        id: 'a-little-cut',
        title: 'A little CUT',
        description: 'Comic for Berliner Fernster 2021',
        thumbnail: '/comics/a_little_cut/1.jpg',
        images: [
            '/comics/a_little_cut/1.jpg',
            '/comics/a_little_cut/2.jpg',
            '/comics/a_little_cut/3.jpg',
            '/comics/a_little_cut/4.jpg',
            '/comics/a_little_cut/5.jpg',
            '/comics/a_little_cut/6.jpg',
            '/comics/a_little_cut/7.jpg',
            '/comics/a_little_cut/8.jpg',
        ],
    },
    {
        id: 'ha!',
        title: 'ha!',
        description: 'Comic for Instagram',
        thumbnail: '/comics/ha!/2.jpg',
        images: [
            '/comics/ha!/0.jpg',
            '/comics/ha!/1.jpg',
            '/comics/ha!/2.jpg',
            '/comics/ha!/3.jpg',
            '/comics/ha!/4.jpg',
            '/comics/ha!/5.jpg',
            '/comics/ha!/6.jpg',
            '/comics/ha!/7.jpg',
            '/comics/ha!/8.jpg',
            '/comics/ha!/9.jpg',
        ],
    },
    {
        id: 'lisa-frank!',
        title: 'Lisa Frank!',
        description: 'Comic for Instagram',
        thumbnail: '/comics/lisa_frank/1.jpg',
        images: [
            '/comics/lisa_frank/1.jpg',
            '/comics/lisa_frank/2.jpg',
            '/comics/lisa_frank/3.jpg',
            '/comics/lisa_frank/4.jpg',
            '/comics/lisa_frank/5.jpg',
            '/comics/lisa_frank/6.jpg',
            '/comics/lisa_frank/7.jpg',
            '/comics/lisa_frank/8.jpg',
        ],
    },
    {
        id: 'hair',
        title: 'Hairass',
        description: 'Comic for Instagram',
        thumbnail: '/comics/hair/1.jpg',
        images: [
            '/comics/hair/1.jpg',
            '/comics/hair/2.jpg',
            '/comics/hair/3.jpg',
            '/comics/hair/4.jpg',
        ],
    },
    {
        id: 'beauty',
        title: 'Beauty',
        description: 'Comic for Instagram',
        thumbnail: '/comics/beauty/1.jpg',
        images: [
            '/comics/beauty/1.jpg',
            '/comics/beauty/2.jpg',
            '/comics/beauty/3.jpg',
            '/comics/beauty/4.jpg',
            '/comics/beauty/5.jpg',
            '/comics/beauty/6.jpg',
        ],
    },
    {
        id: 'wild',
        title: 'Wild',
        description: 'Comic for Instagram',
        thumbnail: '/comics/wild/1.jpg',
        images: [
            '/comics/wild/1.jpg',
            '/comics/wild/2.jpg',
            '/comics/wild/3.jpg',
            '/comics/wild/4.jpg',
        ],
    },
    {
        id: 'speechless',
        title: 'Speechless',
        description: 'Submission for CIB',
        thumbnail: '/comics/speechless/3.jpg',
        images: [
            '/comics/speechless/1.jpg',
            '/comics/speechless/2.jpg',
            '/comics/speechless/3.jpg',
            '/comics/speechless/4.jpg',
            '/comics/speechless/5.jpg',
            '/comics/speechless/6.jpg',
            '/comics/speechless/7.jpg',
            '/comics/speechless/8.jpg',
            '/comics/speechless/9.jpg',
            '/comics/speechless/10.jpg',
            '/comics/speechless/11.jpg',
            '/comics/speechless/12.jpg',
            '/comics/speechless/13.jpg',
            '/comics/speechless/14.jpg',
            '/comics/speechless/15.jpg',
            '/comics/speechless/16.jpg',
            '/comics/speechless/17.jpg',
            '/comics/speechless/18.jpg',
        ],
    },
    {
        id: 'energy',
        title: 'Energy',
        description: 'Comic for Instagram',
        thumbnail: '/comics/energy/energy3.jpg',
        images: ['/comics/energy/ALL.jpg'],
    },
]
