import React from 'react'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

export default function video() {
  return (
    <Layout>
      <div className={styles.containerVideos}>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/Ubm_WsngUHc"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/XawA7O46yJM"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/fndIJmvtEGE"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/bF7MXxzlLTM"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/THXc_fM-r7o"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/lJQ2nw-ZOV4"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/GIxQDxuQNA4"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/ogTeixzDw0Q"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/qHFB1DEnRlM"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/liVf92-ELw0"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/FuHreqftKQA"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/IhajUvDE_LA"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/KQjYNSIFDxM"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
        <iframe
          className={styles.video}
          width="896"
          height="504"
          src="https://www.youtube.com/embed/OeVoV7Q1cMQ"
          frameborder="0"
          allowfullscreen="allowfullscreen"
          mozallowfullscreen="mozallowfullscreen"
          msallowfullscreen="msallowfullscreen"
          oallowfullscreen="oallowfullscreen"
          webkitallowfullscreen="webkitallowfullscreen"
        ></iframe>
      </div>
    </Layout>
  )
}
